# Mac App Store command-line interface (https://github.com/mas-cli/mas)
brew "mas"
# Install ZShell (https://sourabhbajaj.com/mac-setup/iTerm/zsh.html)
brew "zsh"
# Get lightweight comand line json processor
brew "jq"
# ccat is the colorizing cat (https://github.com/owenthereal/ccat)
brew "ccat"
# nvm to control node used node version
brew "nvm"
# install mongoldb
brew "mongodb/brew/mongodb-community"
# install switchaudio-osx to switch audio output from command line
brew "switchaudio-osx"
# install pyenv to manage python versions
brew "pyenv"
# install direnv to manage environment variables
brew "direnv"
# install stripe cli
brew "stripe/stripe-cli/stripe"
# instal watchman to avoid ulimit on watched files
brew "watchman"
# install go language binary
brew "go"
# install jsonnet to work with jsons
brew "jsonnet"
